const secretariesOfState = [
  'John Jay',
  'Thomas Jefferson',
  'Edmund Randolph',
  'Timothy Pickering',
  'John Marshall',
  'James Madison',
  'Robert Smith',
  'James Monroe',
  'John Quincy Adams',
  'Henry Clay',
  'Martin Van Buren',
  'Edward Livingston',
  'Louis McLane',
  'John Forsyth',
  'Daniel Webster',
  'Abel P. Upshur',
  'John C. Calhoun',
  'James Buchanan',
  'John M. Clayton',
  'Edward Everett',
  'William L. Marcy',
  'Lewis Cass',
  'Jeremiah S. Black',
  'William H. Seward',
  'Elihu B. Washburne',
  'Hamilton Fish',
  'William M. Evarts',
  'James G. Blaine',
  'Frederick T. Frelinghuysen',
  'Thomas F. Bayard',
  'John W. Foster',
  'Walter Q. Gresham',
  'Richard Olney',
  'John Sherman',
  'William R. Day',
  'John Hay',
  'Elihu Root',
  'Robert Bacon',
  'Philander C. Knox',
  'William Jennings Bryan',
  'Robert Lansing',
  'Bainbridge Colby',
  'Charles Evans Hughes',
  'Frank B. Kellogg',
  'Henry L. Stimson',
  'Cordell Hull',
  'Edward Stettinius Jr.',
  'James F. Byrnes',
  'George C. Marshall',
  'Dean Acheson',
  'John Foster Dulles',
  'Christian Herter',
  'Dean Rusk',
  'William P. Rogers',
  'Henry Kissinger',
  'Cyrus Vance',
  'Edmund Muskie',
  'Alexander Haig',
  'George Shultz',
  'James Baker',
  'Lawrence Eagleburger',
  'Warren Christopher',
  'Madeleine Albright',
  'Colin Powell',
  'Condoleezza Rice',
  'Hillary Clinton',
  'John Kerry',
  'Rex Tillerson',
  'Mike Pompeo',
  'Antony Blinken',
  'Marco Rubio',
];
